// JOB DESCRIPTIONS
export const JOB_DESCRIPTION_CATEGORIES = []
export const JOB_DESCRIPTION_POSITIONS_NO = []
export const JOB_DESCRIPTION_JOB_STATUS = []

// PANELIST 
export const PANELIST_DESIGINATIONS = []
export const PANELIST_TIME_ZONES = []
export const PANELIST_SKILLS = []